src_dir: src
public_dir: docs

title: Ziyunch's Online Bookmark Collection

bookmarks:
  - name: 我的博客
    url: https://blindwith.science/
    favicon: ziyunch.ico
  - name: Gmail
    url: https://mail.google.com/
    favicon: gmail.ico
  - name: Inbox
    url: https://inbox.google.com/
    favicon: inbox.png
  - name: GitHub
    url: https://github.com/ziyunch
    favicon: github.ico
  - name: Workflowy
    url: https://workflowy.com/
    favicon: workflowy.ico
  - name: Youtube
    url: https://www.youtube.com/
    favicon: youtube-32.png

  - category: 工作相关
  - name: Linkedin
    url: https://www.linkedin.com/
    favicon: linkedin.ico
  - name: Indeed
    url: https://www.indeed.com/
    favicon: indeed.ico
  - name: Glassdoor
    url: https://www.glassdoor.com/
    favicon: glassdoor.ico
  - name: 一亩三分地
    url: https://www.1point3acres.com/bbs/
    favicon: 1point3acres.ico

  - category: 知识问答
  - name: Reddit
    url: https://www.reddit.com/
    favicon: reddit.ico
  - name: Quora
    url: https://www.quora.com/
    favicon: quora.png
  - name: 知乎
    url: https://www.zhihu.com/
    favicon: zhihu.ico
  - name: TED
    url: https://www.ted.com/
    favicon: ted.ico
  - name: Matrix67
    url: http://www.matrix67.com/blog/
  - name: 果壳
    url: https://www.guokr.com/
    favicon: guokr.ico

  - category: 机器学习
  - name: Amazon Science
    url: https://www.amazon.science
    favicon: amazon-32.png
  - name: Deep Learning
    url: http://d2l.ai

  - category: 烧菜觅食
  - name: 下厨房
    url: http://www.xiachufang.com/
    favicon: xiachufang.ico
  - name: 梅玺阁
    url: http://www.yuleshow.com/?cat=257/
    favicon: yuleshow.ico
  - name: Yelp
    url: https://www.yelp.com/
    favicon: yelp.ico
  - name: OpenTable
    url: https://www.opentable.com/
    favicon: opentable.gif
  - name: 生蚝地图
    url: https://boston.eater.com/maps/dollar-oysters-boston/
    favicon: eater.ico

  - category: 购物参考
  - name: Slickdeals
    url: https://slickdeals.net/
    favicon: slickdeals.ico
  - name: Craigslist
    url: https://boston.craigslist.org/
    favicon: craigslist.ico
  - name: Amazon
    url: https://www.amazon.com/
    favicon: amazon.ico
  - name: Ebay
    url: https://www.ebay.com/
    favicon: ebay.ico
  - name: Etsy
    url: https://www.etsy.com/
    favicon: etsy.ico
  - name: 北美省钱快报
    url: https://cn.dealmoon.com/
    favicon: dealmoon.ico
  - name: 英国红领巾
    url: https://www.honglingjin.co.uk/
    favicon: honglingjin.ico

  - category: 读书电影
  - name: 豆瓣
    url: https://www.douban.com/
    favicon: douban.ico
  - name: 开放文学
    url: http://open-lit.com/
    favicon: open-lit.ico
  - name: 书格
    url: https://shuge.org/
    favicon: shuge.ico
  - name: 寐语扫描版古籍
    url: http://kzeng.info/books/
    favicon: kzeng.ico
  - name: 台湾图书馆古籍
    url: http://rbook2.ncl.edu.tw/
  - name: 中国哲学书电子化计划
    url: https://ctext.org/zh/
  - name: 搜韵
    url: https://sou-yun.com/
    favicon: sou-yun.bmp
  - name: Vol.moe
    url: https://vol.moe/
    favicon: volmoe.ico
  - name: 好读
    url: http://www.haodoo.net/
    favicon: haodoo.ico
  - name: 我的小书屋
    url: http://mebook.cc/
    favicon: mebook.ico
  - name: LibGen
    url: http://gen.lib.rus.ec/
    favicon: libgen.ico
  - name: 莎翁全集
    url: http://shakespeare.mit.edu/
    favicon: shakespeare.bmp
  - name: 费曼讲义
    url: http://www.feynmanlectures.caltech.edu/
    favicon: feynmanlectures.ico
  - name: 记忆的性别
    url: https://gailhershatter.sites.ucsc.edu/translation/
  - name: Letterboxd
    url: https://letterboxd.com/
    favicon: letterboxd.ico
  - name: Critics Top 10
    url: https://criticstop10.com/
  - name: 迷影网
    url: http://www.cinepedia.cn/

  - category: 技术社区
  - name: 少数派
    url: https://sspai.com/
    favicon: sspai.ico
  - name: 爱范儿
    url: https://www.ifanr.com/
    favicon: ifanr.ico
  - name: V2EX
    url: https://v2ex.com/
    favicon: v2ex.png
  - name: The Verge
    url: https://www.theverge.com/
    favicon: theverge.ico
  - name: Engadget
    url: https://cn.engadget.com/
    favicon: engadget-160.png

  - category: 实用工具
  - name: FontAwesome
    url: https://fontawesome.com/
    favicon: fontawesome.ico
  - name: Color Generator
    url: https://coolors.co/
    favicon: coolors.png

  - category: 数码外设
  - name: 数字尾巴
    url: http://www.dgtle.com/
    favicon: dgtle.ico
  - name: 装备前线
    url: https://www.zfrontier.com/
    favicon: zfrontier.ico
  - name: MassDrop
    url: https://www.massdrop.com/
    favicon: massdrop.ico
  - name: Chiphell
    url: https://www.chiphell.com/
    favicon: chiphell.ico
  - name: 什么值得买
    url: https://www.smzdm.com/
    favicon: smzdm.ico
  - name: Knewone
    url: https://knewone.com/
    favicon: knewone.ico
  - name: Mobile01
    url: https://www.mobile01.com/
    favicon: mobile01.ico
  - name: RAMA Works
    url: https://ramaworks.store/
    favicon: rama-32.png
  - name: OLKB
    url: https://olkb.com/
    favicon: olkb.ico
  - name: GeekKeys
    url: http://www.geekkeys.com/
  - name: Dwarf-Factory
    url: https://www.dwarf-factory.com/
    favicon: dwarf-factory.ico
  - name: 文具病
    url: http://www.stationeria.net/

  - category: 二次元
  - name: 哔哩哔哩
    url: https://www.bilibili.com/
    favicon: bilibili.ico
  - name: bangumi
    url: http://bgm.tv/
    favicon: bangumi.ico
  - name: ニコニコ
    url: http://sp.nicovideo.jp/
    favicon: niconico.ico
  - name: Akross
    url: http://www.akross.ru/index.cgi?l=e
    favicon: akross.ico
  - name: MyAnimeList
    url: https://myanimelist.net/
    favicon: myanimelist.png
  - name: 比特客栈的文艺复兴
    url: https://bitinn.net/
    favicon: bitinn.ico
  - name: VCB-Studio
    url: https://vcb-s.com/
    favicon: vcb-s.ico
  - name: THX字幕组
    url: https://www.zhengmianshang.me/
  - name: 天使动漫
    url: http://www.tsdm.me/
  - name: A.I.R.nesSub
    url: https://airu.us/

  - category: 手办游戏
  - name: 机核
    url: https://www.gcores.com/
    favicon: gcores.ico
  - name: 乐高
    url: https://www.lego.com/
    favicon: lego.ico
  - name: Brickset
    url: https://brickset.com/
    favicon: brickset.ico
  - name: Bricklink
    url: https://www.bricklink.com/
    favicon: bricklink.ico
  - name: 任天堂
    url: https://www.nintendo.com/
    favicon: nintendo.ico
  - name: Amiibo Database
    url: https://amiibo.life/
    favicon: amiibo.ico
  - name: 任饭的博客
    url: http://www.mariozelda.com/
    favicon: mariozeldalogo-32.png
  - name: 奸笑社
    url: https://www.goodsmile.info/en/
    favicon: goodsmile.ico
  - name: 植物少女园
    url: http://shokuen.com/figure/index.html
  - name: TsumTsum Database
    url: https://www.tsumtsumcentral.com/
  - name: Vinyl Database
    url: http://www.allvinyls.com/
    favicon: allvinyls.ico
  - name: Kidrobot
    url: https://www.kidrobot.com/
    favicon: kidrobot-32.png
  - name: MightyJaxx
    url: https://mightyjaxx.rocks/
    favicon: mightyjaxx.png
  - name: FYE
    url: https://www.fye.com/
    favicon: fye.ico
  - name: MyPlaticHeart
    url: https://www.myplasticheart.com/
    favicon: myplasticheart.ico
  - name: Brosmind
    url: http://www.brosmind.com/
  - name: Sad Sales Man
    url: https://www.sadsalesman.com/
  - name: Scott C
    url: https://thescottcshop.com/
    favicon: thescottcshop.jp2
  - name: Hidden Fortress
    url: http://www.hiddenfortressmanila.com/
    favicon: hiddenfortress.ico
  - name: 2PetalRose
    url: https://2petalrose.bigcartel.com/
  - name: Unbox Industries
    url: http://store.unboxindustries.info/
  - name: PoPaganda
    url: https://popaganda.myshopify.com/

  - category: 户外运动
  - name: Rei
    url: https://www.rei.com/
    favicon: rei.ico
  - name: Dicks
    url: https://www.dickssportinggoods.com/
    favicon: dickssportinggoods.ico
  - name: BackCountry
    url: https://www.backcountry.com/
    favicon: backcountry.ico
  - name: MooseJaw
    url: https://www.moosejaw.com/
    favicon: moosejaw.ico
  - name: BestMade
    url: https://www.bestmadeco.com/
    favicon: bestmadeco.png
  - name: Filson
    url: https://www.filson.com/
    favicon: filson.ico
  - name: Danner
    url: https://www.danner.com/
    favicon: danner.ico
  - name: Camp Brand
    url: https://campbrandgoods.com/
    favicon: campbrandgoods-32.png
  - name: Salmon Sisters
    url: https://aksalmonsisters.com/
    favicon: aksalmonsisters-32.png
  - name: United by Blue
    url: https://unitedbyblue.com/
    favicon: unitedbyblue-32.png
  - name: BackPackers
    url: https://backpackers.com/
    favicon: backpackers.png
  - name: Emalco
    url: https://emalco.com/shop/
    favicon: emalco.png

  - category: 文字摄影
  - name: 杉本博司
    url: https://www.sugimotohiroshi.com/photography/
    favicon: sugimotohiroshi.ico
  - name: Ken Liu
    url: http://kenliu.name/
    favicon: kenliu.ico

  - category: 设计产品
  - name: Tom Dixon
    url: https://www.tomdixon.net/
    favicon: tomdixon.png
  - name: AviationTag
    url: https://www.aviationtag.com/
  - name: Umbra
    url: http://www.umbra.com/
    favicon: umbra.ico
  - name: Artsy
    url: https://www.artsy.net/
    favicon: artsy.ico
  - name: Antler's Gallery
    url: http://www.antlersgallery.com/
    favicon: antlersgallery.png
  - name: Tictail
    url: https://tictail.com/
    favicon: tictail.ico
  - name: Koromiko
    url: https://koromiko.com/
    favicon: koromiko.png
  - name: Art and Article
    url: https://www.artandarticle.com/
    favicon: artandarticle.ico
  - name: Joe Doucet
    url: http://joedoucet.com/
    favicon: joedoucet.jpeg

  - category: 博物馆
  - name: 「大波士顿」
  - name: Museum of Fine Art
    url: https://www.mfa.org/
    favicon: mfa.ico
  - name: Museum of Science
    url: https://www.mos.org/
    favicon: mos.png
  - name: Isabella Gardner Museum
    url: https://www.gardnermuseum.org/
    favicon: gardnermuseum-192.jpg
  - name: Institute of Contemporary Art
    url: https://www.icaboston.org/
    favicon: icaboston.png
  - name: Harvard Museum of Natural History
    url: https://hmnh.harvard.edu/
    favicon: hmnh.gif
  - name: MIT Museum
    url: https://mitmuseum.mit.edu/
    favicon: mit.ico
  - name: Peabody Essex Museum
    url: https://www.pem.org/
    favicon: pem.ico
  - name: Salem Witch Museum
    url: https://salemwitchmuseum.com/
    favicon: salemwitchmuseum.jpeg
  - name: Boston Museum Map
    url: https://www.boston.com/culture/arts/2017/05/04/use-this-map-to-visit-the-boston-areas-many-museums/
    favicon: boston.ico
  - name: Portland Museum of Art
    url: https://www.portlandmuseum.org/
    favicon: portlandmuseum.ico
  - name: Yale Peabody Museum
    url: https://peabody.yale.edu/
    favicon: yalepeabody.ico
  - name: 「纽约」
  - name: The Met
    url: https://metmuseum.org/
    favicon: metmuseum.ico
  - name: MoMA
    url: https://www.moma.org/
    favicon: moma.ico
  - name: MoMA PS1
    url: https://momaps1.org/
    favicon: momaps1.ico
  - name: Guggenheim
    url: https://www.guggenheim.org/
    favicon: guggenheim.jpg
  - name: Whitney Museum of American Art
    url: https://whitney.org/
    favicon: whitney.ico
  - name: Frick Collection
    url: https://www.frick.org/
    favicon: frick.ico
  - name: Neue Galerie
    url: https://www.neuegalerie.org/
    favicon: neuegalerie.ico
  - name: Rubin Museum of Art
    url: http://rubinmuseum.org/
    favicon: rubinmuseum.png
  - name: American Museum of Natural History
    url: https://www.amnh.org/
    favicon: amnh.ico
  - name: Cooper Hewitt
    url: https://www.cooperhewitt.org/
    favicon: cooperhewitt.png
  - name: Noguchi Museum
    url: https://www.noguchi.org/
    favicon: noguchi.png
  - name: 「费城」
  - name: Philadelphia Museum of Art
    url: https://www.philamuseum.org
    favicon: philamuseum.ico
  - name: Franklin Institute
    url: https://www.fi.edu/
    favicon: fi.png
  - name: Penn Museum
    url: https://www.penn.museum/
    favicon: pennmuseum.ico
  - name: 「华盛顿」
  - name: National Museum of Natural History
    url: https://naturalhistory.si.edu/
    favicon: naturalhistorysi.ico
  - name: National Museum of Afican American History & Culture
    url: https://nmaahc.si.edu/
    favicon: nmaahcsi.ico
  - name: National Air and Space Museum
    url: https://airandspace.si.edu/
    favicon: airandspacesi.ico
  - name: 「芝加哥」
  - name: Art Institute Chicago
    url: http://www.artic.edu/
    favicon: artic-196.png
  - name: Field Museum
    url: https://www.fieldmuseum.org/
    favicon: fieldmuseum.png
  - name: MCA Chicago
    url: https://mcachicago.org/
    favicon: mcachicago.png
  - name: 「其他」
  - name: High Museum of Art
    url: https://high.org/
    favicon: high.png
  - name: Hemingway Home & Museum
    url: https://www.hemingwayhome.com/
    favicon: hemingwayhome.jpeg

  - category: 灯塔
  - name: US Lighthouse Society
    url: https://uslhs.org/
    favicon: uslhs.ico
  - name: American Lighthouse Foundation
    url: http://www.lighthousefoundation.org/
    favicon: lighthousefoundation.ico
  - name: USLHS活动
    url: https://uslhs.org/fun/lighthouse-festivals-events/
    favicon: uslhs.ico
  - name: 新英格兰
    url: http://www.newenglandlighthouses.net/
    favicon: lighthouse.ico
  - name: 麻省
    url: https://www.visit-massachusetts.com/state/lighthouses/
  - name: 缅因
    url: http://www.lighthousefoundation.org/maine-open-lighthouse-day/
    favicon: lighthousefoundation.ico
  - name: 新泽西
    url: http://lhchallengenj.org/challMap.php
    favicon: lhchallengenj.ico
  - name: 马里兰
    url: https://cheslights.org/maryland-lighthouse-challenge/
    favicon: cheslights.ico

  - category: 纸牌
  - name: Theory11
    url: https://www.theory11.com/
    favicon: theory11.ico
  - name: 52Aces
    url: http://52aces.de/
    favicon: 52aces.ico
  - name: Playing Arts
    url: https://playingarts.com/
    favicon: playingarts.ico
  - name: The Type Deck
    url: http://thetypedeck.com/
    favicon: thetypedeck.ico
  - name: The Design Deck
    url: http://www.forrestgoods.com/
    favicon: forrestgoods.png
